; (1 3 (5 7) 9)
(define lst (list 1 3 (list 5 7) 9))
(cdr(car(cdr(cdr lst))))
;((7))
(define lst (list ((list 7))))
(car (car lst))
;(1 (2 (3 (4 (5 ( 6 7))))))
(define lst (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 7))))))
  )
(cdr lst) => ((2 (3 (4 (5 (6 7))))))
(car (cdr lst)) => (2 (3 (4 (5 (6 7)))))
(cdr (car (cdr lst))) => ((3 (4 (5 (6 7)))))
(car (cdr (car (cdr lst)))) => (3 (4 (5 (6 7))))
(cdr (car (cdr (car (cdr lst))))) => ((4 (5 (6 7))))
(car (cdr (car (cdr (car (cdr lst)))))) => (4 (5 (6 7)))
(cdr (car (cdr (car (cdr (car (cdr lst))))))) => ((5 (6 7)))
(car (cdr (car (cdr (car (cdr (car (cdr lst)))))))) => (5 (6 7))
(cdr (car (cdr (car (cdr (car (cdr (car (cdr lst))))))))) => ((6 7))
(car (cdr (car (cdr (car (cdr (car (cdr (car (cdr lst)))))))))) =>(6 7)
(cdr (car (cdr (car (cdr (car (cdr (car (cdr (car (cdr lst))))))))))) => 7
