(define (make-vect x y)
  (list x y)
  )
(define (xcor-vect vec)
  (car vec)
  )
(define (ycor-vect vec)
  (cadr vec)
  )
(define (add-vec vec1 vec2)
  (make-vect (+ (xcor-vect vec1) (xcor-vect vec2))
             (+ (ycor-vect vec1) (ycor-vect vec2))
    )
  )
(define (sub-vec vec1 vec2)
  (make-vect (- (xcor-vect vec1) (xcor-vect vec2))
             (- (ycor-vect vec1) (ycor-vect vec2))
             )
  )
(define (multi vec factor)
  (make-vect (* factor (xcor-vect vec))
             (* factor (ycor-vect vec2))
             )
  )
