(define (attach-tag type-tag contens)
  (cons type-tag contens)
  )
(define (type-tag datum)
  (if (pair? datum)
      (car datum)
      (error "BAD TAGGED" datum)
      )
  )
(define (contens datum)
  (if (pair? datum)
      (cdr datum)
      (error "BAD TAGGED" datum)
      )
  )
