(load"1-21.scm")
(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime))
  )
(define (start-prime-test n start-time)
  (if (prime? n) (report-prime (- (runtime) start-time)))
  )
(define (report-prime elapsed-time)
  (display "****")
  (display elapsed-time)
  )
(define (prime? n)
  (= n (smallest-divisor n))
  )
(define (next-odd n)
  (if (odd? n) (+ 2 n)
      (+ 1 n)
      )
  )
(define (odd? n)
  (= 1 (remainder n 2))
  )
(define (create n count)
  (if (> count 0) 
        (if (prime? n) (
                        begin 
                            (display n)
                            (newline)
                            (create (next-odd n) (- count 1))
                        )
                        (create (next-odd n) count )
            )
       (display "Done")
       )
  )
