(define (cont-frac-recu n d k)
  (define (cf i)
    (if (= k i) 
        (/ (n k) (d k))
        (/ (n i) (+ (d i) ( cf (+ i 1))))
        )
    )
  (cf 1)
  )
(define (cont-frac-iter n d k)
  (define (iter i result)
    (if (= i 0) result
        (iter (- i 1)
              (/ (n i) (+ (d i) result))
              )
        )
    )
  (iter (- k 1) (/ (n k) (d k)))
  )
