(define tolerance 0.0000001)
(define (two-point-iter f a b)
  (define (close-enough? v1 v2)
    ( < (abs (- v1 v2)) tolerance )
    )
  (let ( (mid (average a b)))
    (cond 
      ( (close-enough? a b) mid)
      ( (< (f mid) 0) (two-point-iter f mid b))
      (else (two-point-iter f a mid))
      )
    )
    )
;(define (two-point-iter f a b)
  ;(define (close-enough? v1 v2)
    ;(<  (abs (- v1 v2)) tolerance )
    ;)
  ;(let ( (mid (average a b)))
    ;(cond  ( (close-enough? a b) mid)
            ;( (< (f mid) 0)  (two-point-iter f mid b) )
            ;( else (two-point-iter f a mid ))
            ;)
    ;)
  ;)
